### ISSUE TITLE
in ukb-annex, /data/derived/test is ~1.8GB, it should be much smaller

### ISSUE THREAD

**Issue by r03ert0** [r03ert0/ENIGMA-GCTA#4]
the idea is to use `derived/test` to test our scripts in continuous integration. It should be small, but there are `1000genomes_eur.bed`, `.bim` and `.fam` files which together make ~1.7GB.

Maybe the script in `src/test` should delete them after using them?

**Comment by ntraut** [comment]
yes we can either delete or ignore those files.

**Comment by r03ert0** [comment]
do I add it to .gitignore?

**Comment by r03ert0** [comment]
it's maybe better just to delete the files at the end of the script...

**Comment by ntraut** [comment]
I removed the files.
@r03ert0 Would not it be better ignore all the files in `data/derived/test` except from `00.phenotype` and `01.genotype`, since the other file have to be generated for testing?

**Comment by r03ert0** [comment]
great!

ok for ignoring the files. But, when we'll run the code in CircleCI, the files will still be generated and not removed, yes?

**Comment by ntraut** [comment]
They will be generated in the virtual machine. But if we don't ignore them in git, they will be already present before being generated, so it will be more difficult to check if the pipeline work correctly.
